alias a='print -z $(fzf_get_alias)'
alias k='sudo `which kmon` --color 6f849c --accent-color e35760'
alias m='btop -p 0'
alias v='$EDITOR'
alias e='my_eval_var'
alias K='kill -9 '
alias rd='trash-put'
alias ea='direnv allow .'
alias vg='neovide --multigrid --noidle '
alias vx='my_create_script'
alias nf='n -P f'
alias src='omz reload'
alias ddr='dd if=/dev/urandom bs=4K count=1 | base64 > output.dat'
alias vrs='trash-put $HOME/.local/share/nvim/swap/*.swp'
alias vrS='trash-put $HOME/.local/share/nvim/sessions/*.vim'
alias pipi='pip install'
alias pipu='pip install -U'
alias pipl='pip list | less'
alias pipd='pip uninstall'
alias npmi='npm install -g'
alias npmd='npm uninstall'
alias myip='curl http://ipecho.net/plain; echo'
alias tssh='TERM=xterm-256color ssh'
alias sysl='sudo `which sysz`'

alias gcl='git clone'
alias gc='git commit -v; git_current_user_name; git_current_user_email'
alias gclr='git clone --recurse-submodules --jobs $(nproc)'
alias gla='git log --graph --decorate --author=""'
alias gbrc='git branch -m'
alias glr='git pull --rebase'
alias gn='git_current_user_name; git_current_user_email'
alias gsa='git submodule add -b <branch_to_track_if_any> <url>'
alias gsr='git rm <path-to-submodule>'
alias gar='my_add_git_remote'
alias grl='git remote -v'
alias gbrn='git branch -m new_name'
alias gdh='git diff HEAD~1 HEAD'
alias glgr='my_git_log_grep'
alias gcfg='git config user.name "";
git config user.email "";
git_current_user_name; git_current_user_email'
alias gcca='git commit -v --amend --author="$(git_current_user_name) <$(git_current_user_email)>"'

alias ts='tmux new-session -s'
alias ta='tmux attach-session -t'
alias tk='tmux kill-session -t'
alias tK='tmux kill-server'
alias tl='tmux list-sessions'
alias Tn='tmuxinator new'
alias Te='tmuxinator edit'
alias Ts='tmuxinator start'
alias Tl='tmuxinator list'
alias Td='tmuxinator delete'
alias TA='task add'
alias TL='task list'
alias TK='task done'
alias TE='my_modify_taskwarrior_task'

alias -g F='| fzf-tmux'
alias -g H='--help | less'
alias -g S='| sort'
alias -g C='| wc -l'
alias -g T='2>&1 | tee .my.log'
alias -g E='| tail'
alias -g B='| head'

# .zsh/functions.zsh
alias c='my_get_cheats'
alias vt='my_create_edit_tmp'
alias gia='my_create_gitignore'
alias rgf='my_ripgrep_fzf'

# ohmyzsh_plugins/copyfile
alias cpf='copyfile'
# ohmyzsh_plugins/jsontools
alias -g J='| pp_json'
# wfxr/forgit
alias glg='forgit::log'
alias gD='forgit::diff'
alias grh='forgit::reset::head'
alias gCB='forgit::checkout::branch'
alias gbd='forgit::branch::delete'
alias gCC='forgit::checkout::commit'
alias grv='forgit::revert::commit'
alias gcp='forgit::cherry::pick master'
alias gR='forgit::rebase'
