require("colorbuddy").setup()

local Color, colors, Group, groups, styles = require('colorbuddy').setup()

Color.new('black', '#2f2d44')
Color.new('white', '#ffffff')
Color.new('Indent1', '#6dbed7')
Color.new('Indent2', '#61bed7')
Color.new('Indent3', '#68A4B6')
Color.new('Indent4', '#5A8C9B')
Color.new('Indent5', '#4A7A89')
Color.new('Indent6', '#316777')
Color.new('Indent7', '#225E70')
Color.new('Indent8', '#134C5E')
Color.new('red', '#d70000')
Color.new('yellow', '#ffe11a')
Color.new('green', '#54e8ad')
Color.new('blue_light', '#bae4ff')
Color.new('blue', '#6F9FFF')
Color.new('darker_blue', '#506faf')
Color.new('darkest_blue', '#384c75')
Color.new('orange', '#b25f00')
Color.new('dark_orange', '#9b7d03')
Color.new('dark_green', '#338e3f')
Color.new('searchBg', vim.fn.synIDattr(vim.fn.synIDtrans(vim.fn.hlID('Search')), 'bg#'))
Color.new('pink', '#f07eed')

Group.new('StatusLine', colors.none, colors.black)
Group.new('Search', colors.black, colors.searchBg)
Group.new('IndentBlanklineCharHighlightListFirstLevel', colors.Indent1)
Group.new('IndentBlanklineCharHighlightListSecondLevel', colors.Indent2)
Group.new('IndentBlanklineCharHighlightListThirdLevel', colors.Indent3)
Group.new('IndentBlanklineCharHighlightListFourthLevel', colors.Indent4)
Group.new('IndentBlanklineCharHighlightListFifthLevel', colors.Indent5)
Group.new('IndentBlanklineCharHighlightListSixtLevel', colors.Indent6)
Group.new('IndentBlanklineCharHighlightListSeventLevel', colors.Indent7)
Group.new('IndentBlanklineCharHighlightListEigthLevel', colors.Indent8)
Group.new('IndentBlanklineContextChar', colors.red)
Group.new('MyLspReferenceRead', colors.red)
Group.new('MyLspReferenceText', colors.red)
Group.new('MyLspReferenceWrite', colors.red)
Group.new('TerminalWindow', colors.white, colors.black)
Group.new('TerminalBorders', colors.red, colors.red)
